"""Freebuff intelligence engines for RailMind.

E01 — Constraint Engine (engine.constraints)
E02 — Priority Engine (engine.priority)
E03 — Optimization Integration Layer (engine.optimization)
E04 — Scenario Evaluation & Plan Comparison (engine.scenario)
E05 — Scenario Risk Simulation & Uncertainty (engine.simulation)
E06 — Predictive Risk & Uncertainty Intelligence (engine.prediction)
E09 — §16.3 Delay Baseline + §17 CP-SAT Optimization (engine.delay, engine.planner)

Pure Python at the deterministic core. ``engine.planner`` additionally
requires ortools (TRD §72 locked stack); ``engine.delay`` is stdlib+pydantic.
No FastAPI, no SQLAlchemy, no network, no persistence, no clock.
"""

from engine.constraints.engine import ConstraintEngine, ConstraintEvaluation, default_rules
from engine.constraints.result import ConstraintResult, ConstraintEvidence, EngineError
from engine.constraints.types import ConstraintType
from engine.constraints.severity import ConstraintSeverity
from engine.constraints.configuration import ConstraintEngineConfig
from engine.priority.engine import PriorityEngine, classify
from engine.priority.configuration import PriorityEngineConfig
from engine.priority.inputs import PriorityInput, AssetFailureRisk, TaskType
from engine.priority.missing_data import MissingDataPolicy
from engine.priority.result import PriorityResult, FactorScore
from engine.optimization import (
    BlockActivation,
    CandidateSolution,
    ObjectiveBreakdown,
    ObjectiveEvaluator,
    OptimizationConfig,
    PriorityComponent,
    TaskAssignment,
    rank_candidates,
)
from engine.scenario import (
    ComparisonSummary,
    RankedCandidate,
    ScenarioCandidate,
    ScenarioComparator,
    ScenarioComparison,
    evaluate_candidates,
    validate_candidates,
)
from engine.simulation import (
    BlockRiskProfile,
    BlockWindow,
    C6_DURATION_FEASIBILITY,
    C7_WINDOW_BOUNDS,
    DurationBand,
    DurationDistribution,
    PlanSimulationResult,
    SampleSummary,
    SimulationConfig,
    simulate_block,
    simulate_plan,
    validate_block_windows,
)
from engine.delay import (
    CLASS_CASCADING,
    CLASS_DIRECT,
    CLASS_UNAFFECTED,
    DELAY_ALGORITHM,
    AffectedTrain,
    DelayFeatures,
    DelayModelConfig,
    DelayPredictionResult,
    GraphPropagationDelayModel,
    TrainDelayRecord,
)
from engine.planner import (
    C1_ASSIGNMENT,
    C2_ACTIVATION,
    C3_QUALIFICATION,
    C4_CREW_CAPACITY,
    C5_SECTION_EXCLUSIVITY,
    C6_DURATION_FEASIBILITY,
    C7_WINDOW_BOUNDS,
    C8_PRECEDENCE,
    C9_DEADLINE,
    BlockActivationResult,
    ConstraintTraceEntry,
    CpSatPlanner,
    CrewPool,
    GeneratedPlan,
    PlannerConfig,
    PlannerError,
    PlannerInput,
    PlannerResult,
    PlannerModel,
    SolveEvidence,
    TaskAssignmentResult,
    TaskInput,
    WindowInput,
)
from engine.prediction import (
    ASSET_TYPE_SCORES,
    DurationFeatures,
    DurationPredictionResult,
    DurationPredictionWindow,
    DurationPredictor,
    FailureRiskFeatures,
    FailureRiskPredictionResult,
    FailureRiskPredictor,
    ModelMetadata,
    ModelPredictionError,
    ModelNotAvailableError,
    ModelStatus,
    P10_FACTOR,
    P90_FACTOR,
    PredictionBase,
    PredictionConfig,
    PredictionModel,
    PredictionProvenance,
    WEIGHTS,
    duration_model_metadata,
    failure_risk_model_metadata,
    feature_schema_version,
    validate_duration_features,
    validate_failure_risk_features,
)
from engine._version import (
    CONSTRAINT_SET_ID,
    CONSTRAINT_SET_VERSION,
    DELAY_MODEL_ID,
    DELAY_MODEL_VERSION,
    DURATION_MODEL_ID,
    DURATION_MODEL_VERSION,
    ENGINE_VERSION,
    FAILURE_RISK_MODEL_ID,
    FAILURE_RISK_MODEL_VERSION,
    PLANNER_MODEL_ID,
    PLANNER_MODEL_VERSION,
    PREDICTION_MODEL_ID,
    PREDICTION_MODEL_VERSION,
    OPTIMIZATION_MODEL_ID,
    OPTIMIZATION_MODEL_VERSION,
    PRIORITY_MODEL_ID,
    PRIORITY_MODEL_VERSION,
    SCENARIO_MODEL_ID,
    SCENARIO_MODEL_VERSION,
    SIMULATION_MODEL_ID,
    SIMULATION_MODEL_VERSION,
)

__all__ = [
    "ConstraintEngine",
    "default_rules",
    "ConstraintEvaluation",
    "ConstraintResult",
    "ConstraintEvidence",
    "EngineError",
    "ConstraintType",
    "ConstraintSeverity",
    "ConstraintEngineConfig",
    "PriorityEngine",
    "classify",
    "PriorityEngineConfig",
    "PriorityInput",
    "AssetFailureRisk",
    "TaskType",
    "MissingDataPolicy",
    "PriorityResult",
    "FactorScore",
    "OptimizationConfig",
    "TaskAssignment",
    "BlockActivation",
    "CandidateSolution",
    "ObjectiveEvaluator",
    "ObjectiveBreakdown",
    "PriorityComponent",
    "rank_candidates",
    "ScenarioCandidate",
    "ScenarioComparator",
    "ScenarioComparison",
    "RankedCandidate",
    "ComparisonSummary",
    "evaluate_candidates",
    "validate_candidates",
    "SimulationConfig",
    "DurationDistribution",
    "DurationBand",
    "BlockWindow",
    "validate_block_windows",
    "simulate_block",
    "simulate_plan",
    "PlanSimulationResult",
    "BlockRiskProfile",
    "SampleSummary",
    "C6_DURATION_FEASIBILITY",
    "C7_WINDOW_BOUNDS",
    "PredictionModel",
    "ModelPredictionError",
    "ModelNotAvailableError",
    "ModelMetadata",
    "ModelStatus",
    "feature_schema_version",
    "DurationFeatures",
    "DurationPredictionWindow",
    "FailureRiskFeatures",
    "validate_duration_features",
    "validate_failure_risk_features",
    "DurationPredictor",
    "duration_model_metadata",
    "P10_FACTOR",
    "P90_FACTOR",
    "FailureRiskPredictor",
    "failure_risk_model_metadata",
    "WEIGHTS",
    "ASSET_TYPE_SCORES",
    "DurationPredictionResult",
    "FailureRiskPredictionResult",
    "PredictionBase",
    "PredictionProvenance",
    "PredictionConfig",
    "CRITICALITY_SCORES",
    "CONSTRAINT_SET_ID",
    "CONSTRAINT_SET_VERSION",
    "ENGINE_VERSION",
    "PRIORITY_MODEL_ID",
    "PRIORITY_MODEL_VERSION",
    "OPTIMIZATION_MODEL_ID",
    "OPTIMIZATION_MODEL_VERSION",
    "SCENARIO_MODEL_ID",
    "SCENARIO_MODEL_VERSION",
    "SIMULATION_MODEL_ID",
    "SIMULATION_MODEL_VERSION",
    "PREDICTION_MODEL_ID",
    "PREDICTION_MODEL_VERSION",
    "DURATION_MODEL_ID",
    "DURATION_MODEL_VERSION",
    "FAILURE_RISK_MODEL_ID",
    "FAILURE_RISK_MODEL_VERSION",
    "DELAY_MODEL_ID",
    "DELAY_MODEL_VERSION",
    "PLANNER_MODEL_ID",
    "PLANNER_MODEL_VERSION",
    "AffectedTrain",
    "DelayFeatures",
    "DelayModelConfig",
    "DelayPredictionResult",
    "GraphPropagationDelayModel",
    "TrainDelayRecord",
    "DELAY_ALGORITHM",
    "CLASS_DIRECT",
    "CLASS_CASCADING",
    "CLASS_UNAFFECTED",
    "CpSatPlanner",
    "PlannerConfig",
    "PlannerError",
    "PlannerInput",
    "PlannerResult",
    "PlannerModel",
    "TaskInput",
    "WindowInput",
    "CrewPool",
    "GeneratedPlan",
    "SolveEvidence",
    "TaskAssignmentResult",
    "BlockActivationResult",
    "ConstraintTraceEntry",
    "C1_ASSIGNMENT",
    "C2_ACTIVATION",
    "C3_QUALIFICATION",
    "C4_CREW_CAPACITY",
    "C5_SECTION_EXCLUSIVITY",
    "C6_DURATION_FEASIBILITY",
    "C7_WINDOW_BOUNDS",
    "C8_PRECEDENCE",
    "C9_DEADLINE",
]
