from typing import List, Optional, Protocol
from app.domain.models.infrastructure import RailwayAsset, TrackSection, Corridor
from app.domain.models.maintenance import MaintenanceTask, Defect
from app.domain.models.operations import Train, TrainPath, OperationalWindow, TrainImpact
from app.domain.models.planning import Plan

class InfrastructureRepository(Protocol):
    def get_all_assets(self, page: int, page_size: int) -> tuple[List[RailwayAsset], int]: ...
    def get_asset_by_id(self, asset_id: str) -> Optional[RailwayAsset]: ...
    def get_all_track_sections(self, page: int, page_size: int) -> tuple[List[TrackSection], int]: ...
    def get_track_section_by_id(self, section_id: str) -> Optional[TrackSection]: ...
    def get_all_corridors(self, page: int, page_size: int) -> tuple[List[Corridor], int]: ...
    def get_corridor_by_id(self, corridor_id: str) -> Optional[Corridor]: ...

class OperationsRepository(Protocol):
    def get_all_trains(self, page: int, page_size: int) -> tuple[List[Train], int]: ...
    def get_train_by_id(self, train_id: str) -> Optional[Train]: ...
    def get_all_train_paths(self, page: int, page_size: int) -> tuple[List[TrainPath], int]: ...
    def get_all_operational_windows(self, page: int, page_size: int) -> tuple[List[OperationalWindow], int]: ...
    def get_all_train_impacts(self, page: int, page_size: int) -> tuple[List[TrainImpact], int]: ...

class MaintenanceRepository(Protocol):
    def get_all_tasks(self, page: int, page_size: int) -> tuple[List[MaintenanceTask], int]: ...
    def get_task_by_id(self, task_id: str) -> Optional[MaintenanceTask]: ...
    def get_all_defects(self, page: int, page_size: int) -> tuple[List[Defect], int]: ...
    def get_defect_by_id(self, defect_id: str) -> Optional[Defect]: ...

class PlanRepository(Protocol):
    def get_all(self, page: int, page_size: int) -> tuple[List[Plan], int]: ...
    def get_by_id(self, plan_id: str) -> Optional[Plan]: ...
    def save(self, plan: Plan) -> None: ...
